apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-conf
  labels:
    app: redis-conf
data:
  redis.conf: |
    bind 0.0.0.0
    protected-mode yes
    port 6379
    tcp-backlog 2048
    timeout 0
    tcp-keepalive 300
    daemonize no
    supervised no
    pidfile /var/run/redis.pid
    loglevel notice
    logfile /data/redis.log
    databases 50
    always-show-logo yes
    stop-writes-on-bgsave-error yes
    rdbcompression yes
    rdbchecksum yes
    dbfilename dump.rdb
    dir /data
    masterauth zhuyimin
    replica-serve-stale-data yes
    replica-read-only no
    repl-diskless-sync no
    repl-diskless-sync-delay 5
    repl-disable-tcp-nodelay no
    replica-priority 100
    # requirepass 123456
    maxclients 32768
    #maxmemory 6g
    maxmemory-policy allkeys-lru
    lazyfree-lazy-eviction no
    lazyfree-lazy-expire no
    lazyfree-lazy-server-del no
    replica-lazy-flush no
    appendonly yes
    appendfilename "appendonly.aof"
    appendfsync everysec
    no-appendfsync-on-rewrite no
    auto-aof-rewrite-percentage 100
    auto-aof-rewrite-min-size 64mb
    aof-load-truncated yes
    aof-use-rdb-preamble yes
    lua-time-limit 5000
    cluster-enabled no
    cluster-config-file /data/nodes.conf
    cluster-node-timeout 15000
    slowlog-log-slower-than 10000
    slowlog-max-len 128
    latency-monitor-threshold 0
    notify-keyspace-events ""
    hash-max-ziplist-entries 512
    hash-max-ziplist-value 64
    list-max-ziplist-size -2
    list-compress-depth 0
    set-max-intset-entries 512
    zset-max-ziplist-entries 128
    zset-max-ziplist-value 64
    hll-sparse-max-bytes 3000
    stream-node-max-bytes 4096
    stream-node-max-entries 100
    activerehashing yes
    client-output-buffer-limit normal 0 0 0
    client-output-buffer-limit replica 256mb 64mb 60
    client-output-buffer-limit pubsub 32mb 8mb 60
    hz 10
    dynamic-hz yes
    aof-rewrite-incremental-fsync yes
    rdb-save-incremental-fsync yes

---

apiVersion: v1
kind: Service
metadata:
  name: yaf-redis
spec:
  type: NodePort
  selector:
    app: yaf-redis
  ports:
  - port: 6379
    targetPort: 6379
    nodePort: 30001

---

apiVersion: apps/v1 
kind: Deployment
metadata:
  name: yaf-redis
spec:
  selector: # 选择器
    matchLabels: # 标签匹配
      app: yaf-redis
  replicas: 1
  template:
    metadata:
      labels:
        app: yaf-redis
    spec:
      containers:
        - name: yaf-redis
          image: redis
          command: ["redis-server", "/etc/redis.conf"]
          imagePullPolicy: IfNotPresent
          resources: {}
          ports:
            - containerPort: 6379
          volumeMounts:
            - mountPath: /data
              name: yaf-redis-data
            - mountPath: /etc/redis.conf
              subPath: redis.conf
              name: redis-conf
      volumes:
        - name:  yaf-redis-data
          hostPath:
            path:  /Users/zhuyimin/docker/k8s/docker-desktop/yaf/redis
        - name: redis-conf
          configMap:
            name: redis-conf